F_challenge/F_challenge/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from f_app import views as fv

urlpatterns = [
    url(r'^help/',include('f_app.urls')),
    url(r'^user/',include('appTwo.urls')),
    url(r'^um/',include('userModels.urls')),
    url(r'^form/',fv.frms),
    url(r'^show/',fv.show),
    url(r'^$',fv.index,name="index"),
    path('admin/', admin.site.urls),
]

F_challenge/appTwo/urls.py
from django.conf.urls import url
from appTwo import views

app_name = 'appTwo'
urlpatterns = [
    url(r'^signup/',views.users,name='register'),
    url(r'^$',views.index,name='User Home'),


]

F_challenge/f_app/urls.py
from django.conf.urls import url
from f_app import views


urlpatterns = [
    url(r'^ext/',views.extent_help,name='exthelp'),
    url(r'^$',views.help,name='help'),


]

F_challenge/userModels/urls.py
from django.conf.urls import url

from userModels import views

app_name='userModels'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^register/',views.register,name="register"),
    url(r'^logout/',views.user_logout,name="logout"),
    url(r'^login/',views.user_login,name="login"),
]

F_challenge/appTwo/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254,unique=True)

F_challenge/f_app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
	top_name=models.CharField(max_length=264,unique=True)
	def __str__(self):
		return self.top_name

class Webpage(models.Model):
	topic=models.ForeignKey(Topic,on_delete=models.PROTECT)
	name=models.CharField(max_length=264,unique=True)
	url=models.URLField(unique=True)
	def __str__(self):
		return self.name
#,on_delete=models.PROTECT
class AccessRecord(models.Model):
	name = models.ForeignKey(Webpage,on_delete=models.PROTECT)
	date= models.DateField()
	def __str__(self):
		return str(self.name)

F_challenge/userModels/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user= models.OneToOneField(User,on_delete=models.PROTECT)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

F_challenge/appTwo/forms.py
from django import forms
from appTwo.models import User

class NewUser(forms.ModelForm):
    class Meta:
        model= User
        fields= '__all__'

        

F_challenge/f_app/forms.py
from django import forms

class FormName(forms.Form):
    name= forms.CharField()
    email= forms.EmailField()
    text= forms.CharField(widget=forms.Textarea)

F_challenge/userModels/forms.py
from django import forms
from django.contrib.auth.models import User
from userModels.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('first_name','last_name','username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model= UserProfileInfo
        fields=('portfolio_site','profile_pic')

F_challenge/appTwo/views.py
from django.shortcuts import render
#from django.http import HttpResponse
#from appTwo.models import User
from appTwo.forms import NewUser

# Create your views here.
def index(request):
    return render(request,'apptwo/index.html')

def users(request):
    form= NewUser()

    if request.method == "POST":
        form = NewUser(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('Error !!! Form Invalid')
    return render(request,'apptwo/users.html',{'form':form})

F_challenge/f_app/views.py
from django.shortcuts import render
from . import forms
from f_app.models import AccessRecord,Webpage,AccessRecord


# Create your views here.
def index(request):
    my_dict={'cont':'This is the landing page'}
    return render(request,'index.html',context=my_dict)

def help(request):
    my_dict={'helpp':'What help do you want'}
    return render(request,'help.html',context=my_dict)

def extent_help(request):
    my_dict={'helpp':'this is external'}
    return render(request,'help.html',context=my_dict)

def show(request):
    webpages_list=AccessRecord.objects.order_by('date')
    date_dict={'access_records':webpages_list}
    return render(request,'show.html',context=date_dict)


def frms(request):
    form=forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print(" Validation sucess")
            print("Name"+form.cleaned_data['name'])
    return render(request,'form.html',{'form':form})

F_challenge/userModels/views.py
from django.shortcuts import render

# Create your views here.
from userModels.forms import UserForm,UserProfileInfoForm
# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
# from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request,'usermodels/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('userModels:index'))




def register(request):
    registered= False
    if request.method== 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
                print(request.FILES['profile_pic'])
            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm
        profile_form=UserProfileInfoForm
    return render(request,'usermodels/register.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})



def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('userModels:index'))
            else:
                return HttpResponse("Account Not Active !!!")
        else:
            return HttpResponse("Invalid Login Details Supplied")
    else:
        return render(request,"usermodels/login.html")

F_challenge/templates/apptwo/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
    <h1>Welcome !</h1>
    <h2> Go to /signup to signup</h2>

  </body>
</html>

F_challenge/templates/apptwo/users.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title></title>
  </head>
  <body>

    <div class="container">
      <h1>Please SignUp Here !</h1>

      <form method="post">
        {{form.as_p}}
        {% csrf_token %}

        <input type="submit" class="btn btn-primary" value="Submit">

      </form>


    </div>
  </body>
</html>

F_challenge/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/home.css">
</head>
	<body>


		<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">

			<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">OOOlala</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="#" class="navbar-brand" id="brandname">404 Not Found</a>
			</div>

			<div class="collapse navbar-collapse"id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="#">Home</a></li>
					<li><a href="#">Projects</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">

					<li><a href="#">Log In</a></li>
					<li><a href="#">Sign Up</a></li>

				</ul>
			</div>


		</div>
		</nav>



<div class="container">
  {% block body_block %}
  {% endblock %}
</div>




		<script
			src="http://code.jquery.com/jquery-3.1.1.js"
			integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
			crossorigin="anonymous"
		>
		</script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
		</script>






  </body>
</html>

F_challenge/templates/form.html
<!DOCTYPE html>
{% extends "base.html" %}



{% block body_block %}
      <form class="" action="index.html" method="post">
        {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}  

F_challenge/templates/help.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Help</title>
  </head>
  <body>
    <h1>Heloo this is help page</h1>
    {{helpp}}
  </body>
</html>

F_challenge/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{%static "css/mystyle.css"%}"/>
    <title></title>
  </head>
  <body>
    <h1>hello this is home page</h1>
    <img src="{%static "images/screenshot.png"%}" alt="">
  </body>
</html>

F_challenge/templates/show.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{%static "css/mystyle.css"%}"/>
    <title>Django level Two</title>
  </head>
  <body>

  <a href = "{% url 'appTwo:register' %}"> <h1>hello this is Show page</h1> </a>  
    <h2>Here sre your Access Records</h2>

    <div class="djangtwo">

      {% if access_records %}
      <table>
        <thead>
          <th>Site Name</th>
          <th>Date Accessed</th>
        </thead>
         {% for acc in access_records %}
          <tr>
            <td>{{acc.name}}</td>
            <td>{{acc.date}}</td>
          </tr>
        {% endfor %}


      </table>
      {% else %}
        <p> No Access Records Found </p>
      {% endif %}
    </div>


  </body>
</html>

F_challenge/templates/usermodels/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="css/home.css">
</head>
	<body>


		<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">

			<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">OOOlala</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="{% url 'index' %}" class="navbar-brand" id="brandname">404 Not Found</a>
			</div>

			<div class="collapse navbar-collapse"id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="#">Home</a></li>
					<li><a href="#">Projects</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">


          {% if user.is_authenticated %}
          <li><a href="#">Hello,{{user.first_name}}</a></li>
          <li><a href="{% url 'userModels:logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'userModels:login' %}">Log In</a></li>
					<li><a href="{% url 'userModels:register' %}">Sign Up</a></li>
          {% endif %}

				</ul>
			</div>


		</div>
		</nav>


<br><br>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>




		<script
			src="http://code.jquery.com/jquery-3.1.1.js"
			integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
			crossorigin="anonymous"
		>
		</script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
		</script>






  </body>
</html>

F_challenge/templates/usermodels/index.html
{% extends "usermodels/base.html" %}

{% block body_block %}

<h1>Home Page</h1>
{% endblock %}

F_challenge/templates/usermodels/login.html
{% extends "usermodels/base.html" %}

{% block body_block %}

<div class="jumbotron">
{% if user.is_authenticated %}
<h1>Hello, {{user.first_name}} You are already Logged In</h1>

{% else %}
<h1>Please Login !</h1>

<form action="{% url 'userModels:login' %}" method="post">
  {% csrf_token %}
  <label for="username">Username :</label>
  <input type="text" name="username" placeholder="Enter username">
  <label for="password">Password :</label>
  <input type="password" name="password">


  <input type="submit" name="" value="Login">
</form>

{% endif %}
</div>
{% endblock %}

F_challenge/templates/usermodels/register.html
{% extends "usermodels/base.html" %}

{% block body_block %}


{% if user.is_authenticated %}
<h1>Hello, {{user.first_name}} You are Logged In, Please <a href="{% url 'userModels:logout' %}">Logout</a> to Register for another account</h1>

{% else %}

<div class="jumbotron">
{% if registered %}
<h1>Thank You For registeristering</h1>
{% else %}
<h1>Register Here !</h1>
<h2>Please fill out the form </h2>
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <input type="submit" name="" value="Register">
</form>
{% endif %}
{% endif %}
</div>
{% endblock %}